### ISSUE TITLE
can not add recipes from foodnetwork.com

### ISSUE THREAD

**Issue by geeseven** [mrzapp/nextcloud-cookbook#115]
Greetings,

I am running into some issues adding recipes from foodnetwork.com like the following:

https://www.foodnetwork.com/recipes/alton-brown/shepherds-pie-recipe2-1942900

The site does offer schema.org json data.

<details>
<summary>long and ugly curl output</summary>
 <script type="application/ld+json">[{"@context":"http://schema.org","@type":"Recipe","mainEntityOfPage":true,"name":"Shepherd's Pie","url":"https://www.foodnetwork.com/recipes/alton-brown/shepherds-pie-recipe2-1942900","headline":"Shepherd's Pie","description":"When you're in the mood for a meaty, savory comfort-food classic, serve Alton Brown's Shepherd's Pie from Good Eats on Food Network.","author":[{"@type":"Person","name":"Alton Brown","url":"https://www.foodnetwork.com/profiles/talent/alton-brown"}],"image":{"@type":"ImageObject","url":"https://food.fnr.sndimg.com/content/dam/images/food/fullset/2011/7/26/2/EA1206_shepherds-pie_s4x3.jpg.rend.hgtvcom.406.305.suffix/1383862635744.jpeg","height":"406","width":"305"},"datePublished":"2015-05-31T09:03:36.964-04:00","dateModified":"2014-01-16T17:16:06.680-05:00","publisher":{"@type":"Organization","name":"Food Network","url":"https://www.foodnetwork.com","logo":{"@type":"ImageObject","url":"https://food.fnr.sndimg.com/etc/clientlibs/assets/images/food/fn-logo-flat-60x60.png","height":"60","width":"60"}},"keywords":"British,European Recipes,Shepherd's Pie Recipes,Tomato,Beans and Legumes,Pea Recipes,Lamb Recipes,Onion Recipes,Beef,Corn Recipes,Main Dish,Recipes for a Crowd","cookTime":"P0Y0M0DT0H45M0.000S","prepTime":"P0Y0M0DT0H45M0.000S","totalTime":"P0Y0M0DT1H30M0.000S","recipeIngredient":["1 1/2 pounds russet potatoes","1/4 cup half-and-half","2 ounces unsalted butter","3/4 teaspoon kosher salt","1/4 teaspoon freshly ground black pepper","1 egg yolk","2 tablespoons canola oil","1 cup chopped onion","2 carrots, peeled and diced small","2 cloves garlic, minced","1 1/2 pounds ground lamb","1 teaspoon kosher salt","1/2 teaspoon freshly ground black pepper","2 tablespoons all-purpose flour","2 teaspoons tomato paste","1 cup chicken broth","1 teaspoon Worcestershire sauce","2 teaspoons freshly chopped rosemary leaves","1 teaspoon freshly chopped thyme leaves","1/2 cup fresh or frozen corn kernels","1/2 cup fresh or frozen English peas"],"recipeInstructions":[{"@type":"HowToStep","text":"Peel the potatoes and cut into 1/2-inch dice. Place in a medium saucepan and cover with cold water. Set over high heat, cover and bring to a boil. Once boiling, uncover, decrease the heat to maintain a simmer and cook until tender and easily crushed with tongs, approximately 10 to 15 minutes. Place the half-and-half and butter into a microwave-safe container and heat in the microwave until warmed through, about 35 seconds. Drain the potatoes in a colander and then return to the saucepan. Mash the potatoes and then add the half and half, butter, salt and pepper and continue to mash until smooth. Stir in the yolk until well combined."},{"@type":"HowToStep","text":"Preheat the oven to 400 degrees F."},{"@type":"HowToStep","text":"While the potatoes are cooking, prepare the filling. Place the canola oil into a 12-inch saute pan and set over medium high heat. Once the oil shimmers, add the onion and carrots and saute just until they begin to take on color, approximately 3 to 4 minutes. Add the garlic and stir to combine. Add the lamb, salt and pepper and cook until browned and cooked through, approximately 3 minutes. Sprinkle the meat with the flour and toss to coat, continuing to cook for another minute. Add the tomato paste, chicken broth, Worcestershire, rosemary, thyme, and stir to combine. Bring to a boil, reduce the heat to low, cover and simmer slowly 10 to 12 minutes or until the sauce is thickened slightly."},{"@type":"HowToStep","text":"Add the corn and peas to the lamb mixture and spread evenly into an 11 by 7-inch glass baking dish. Top with the mashed potatoes, starting around the edges to create a seal to prevent the mixture from bubbling up and smooth with a rubber spatula. Place on a parchment lined half sheet pan on the middle rack of the oven and bake for 25 minutes or just until the potatoes begin to brown. Remove to a cooling rack for at least 15 minutes before serving."}],"aggregateRating":{"@type":"AggregateRating","ratingValue":4.8,"reviewCount":571},"recipeYield":"8 servings","review":[{"@type":"Review","author":{"@type":"Person","name":"Jakers"},"reviewRating":{"@type":"Rating","ratingValue":5,"worstRating":"1","bestRating":"5"},"reviewBody":"So yummy!  I made the recipe exactly as written but I did substitute ground turkey for the lamb...oh, and instead of corn I used Lima beans....and instead of peas I used broccoli....and added mushrooms..but basically the exact recipe.  And as recommended by others I doubled the salt, pepper and worcheshire.  Best Sheppard\u2019s pie ever!  Oh yeah, and I also added a can of cream of chicken soup, white wine and a bit of cayenne pepper.  Thanks Alton for a great recipe!!  By now I hope you realize that I am joking!  I truly did make this recipe EXACTLY as written and it\u2019s was delicious!","datePublished":"2018-09-20"},{"@type":"Review","author":{"@type":"Person","name":"azuredivina"},"reviewRating":{"@type":"Rating","ratingValue":5,"worstRating":"1","bestRating":"5"},"reviewBody":"WARNING: Eating this can cause bloating, drowsiness, and aggressiveness. It is so delicious, you may eat up to 3 (or 4) servings. Two people may come close to eating it within a single day and they may even fight over leftovers. Further symptoms include immediate thoughts of acquiring more ingredients to cook this again the following day, leading to a life of depleted funds and expanding waistlines. Proceed with caution.<br />","datePublished":"2015-10-19"},{"@type":"Review","author":{"@type":"Person","name":"Anonymous"},"reviewRating":{"@type":"Rating","ratingValue":4,"worstRating":"1","bestRating":"5"},"reviewBody":"Great recipe! Just one piece of advice ... Go with 90% lean meat, or drain/skim the excess fat after cooking the meat. I thought the flour would absorb it in my 85% lean ground beef, but it was far too greasy by the time it made it to the plate. Otherwise, I'd make it again, no hesitation. My picky three year old ate it too!","datePublished":"2017-03-20"},{"@type":"Review","author":{"@type":"Person","name":"Anonymous"},"reviewRating":{"@type":"Rating","ratingValue":5,"worstRating":"1","bestRating":"5"},"reviewBody":"<span>I've made this several times and it turns out great every time. Sometimes I measure - sometimes I don't. Sometimes I use lamb - sometimes I use ground meat, or even ground chicken. I've used fresh hetbs - and bottled. I prefer fresh, but it is still great with bottled. My son is sensitive to dairy so I now mash my potatoes with roasted garlic, olive oil, chicken broth and a little soy milk. Even with these alterations it is still delicious! I usually make it in bulk and store unbaked shepherd's pie in the freezer for another night. <\/span><br /><br /><span>Read more at: http://www.foodnetwork.com/recipes/alton-brown/shepherds-pie-recipe2.html#communityReviews?oc=linkback<\/span>","datePublished":"2017-01-09"},{"@type":"Review","author":{"@type":"Person","name":"Anonymous"},"reviewRating":{"@type":"Rating","ratingValue":5,"worstRating":"1","bestRating":"5"},"reviewBody":"Outstanding but not enough potato if we follow the recipe. We should go for 2lbs instead of 1.5.","datePublished":"2017-06-11"},{"@type":"Review","author":{"@type":"Person","name":"Victoria M."},"reviewRating":{"@type":"Rating","ratingValue":5,"worstRating":"1","bestRating":"5"},"reviewBody":"<span>I've made this twice now but I used ground turkey due to chronic pancreatitis and lamb is bad for me. Both times it was amazing and my family gobbled it up! Great recipe Alton! And before anyone comments on my review that I didn't make \"shepherd's\" pie, I know that and I don't care. I used what was best for my health and otherwise followed the recipe exactly. <\/span><br />","datePublished":"2018-04-02"},{"@type":"Review","author":{"@type":"Person","name":"Anonymous"},"reviewRating":{"@type":"Rating","ratingValue":5,"worstRating":"1","bestRating":"5"},"reviewBody":"I make shepherd\u2019s pie when I have leftover mashed potatoes. The filling from this recipe is my go-to source. Over the years I\u2019ve tweaked it to our tastes: I <span>use ground beef, a whole can of tomato paste, and extra Worcestershire sauce.  Yummo! <\/span>","datePublished":"2019-10-05"},{"@type":"Review","author":{"@type":"Person","name":"Anonymous"},"reviewRating":{"@type":"Rating","ratingValue":5,"worstRating":"1","bestRating":"5"},"reviewBody":"There are many comments that this recipe is just missing something - and I know what it is.  Just add 2 pints of Guinness beer - add one to the recipe, and enjoy one yourself.  I just made a double portion (to send over some to the neighbors).  And it came out perfect.  (When doubling ingredients, don\u2019t forget to double the # of pints needed).  You\u2019re welcome.","datePublished":"2018-12-01"},{"@type":"Review","author":{"@type":"Person","name":"Dustin A."},"reviewRating":{"@type":"Rating","ratingValue":5,"worstRating":"1","bestRating":"5"},"reviewBody":"After botching my last attempt at a food network recipe and attempting sodium poisoning on my family, I redeemed myself with this Shepherd's Pie recipe.   Everyone loved it.","datePublished":"2018-09-13"},{"@type":"Review","author":{"@type":"Person","name":"Anonymous"},"reviewRating":{"@type":"Rating","ratingValue":5,"worstRating":"1","bestRating":"5"},"reviewBody":"Whole family LOVED it. I also used beef instead of lamb and instead of broth added saved rib drippings from an earlier meal. Sooooo flavourful ","datePublished":"2017-05-03"}],"video":{"@type":"VideoObject","name":"Good Eats Shepherd's Pie","description":"Shepherd's pie is the perfect way to get your kids to eat their vegetables.","duration":"PT0H2M36S","thumbnailUrl":"https://food.fnr.sndimg.com/content/dam/images/food/video/0/01/016/0169/0169268.jpg.rend.hgtvcom.406.229.suffix/1478893631621.jpeg","contentUrl":"https://www.foodnetwork.com/videos/good-eats-shepherds-pie-0169268","embedUrl":"http://link.theplatform.com/s/ip77QC/8_JcA6zpLE8t?format=SMIL&MBR=true","uploadDate":"2018-11-06T18:00:41.080-05:00"},"recipeCuisine":"european","recipeCategory":"main-dish"}, {"@context":"http://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"item":{"@id":"https://www.foodnetwork.com","name":"Home"}},{"@type":"ListItem","position":2,"item":{"@id":"https://www.foodnetwork.com/recipes","name":"Recipes"}},{"@type":"ListItem","position":3,"item":{"@id":"https://www.foodnetwork.com/recipes/alton-brown","name":"Alton Brown"}}]}, {"@context":"http://schema.org","@type":"ItemList","itemListElement":[{"@type":"SiteNavigationElement","url":"https://www.foodnetwork.com/recipes","position":1,"name":"Recipes"},{"@type":"SiteNavigationElement","url":"https://www.foodnetwork.com/shows","position":2,"name":"Shows"},{"@type":"SiteNavigationElement","url":"https://www.foodnetwork.com/profiles","position":3,"name":"Chefs"},{"@type":"SiteNavigationElement","url":"https://www.foodnetwork.com/restaurants","position":4,"name":"Restaurants"},{"@type":"SiteNavigationElement","url":"https://www.foodnetwork.com/videos","position":5,"name":"Videos"},{"@type":"SiteNavigationElement","url":"https://www.foodnetwork.com/magazine","position":6,"name":"Magazine"},{"@type":"SiteNavigationElement","url":"https://www.foodnetwork.com/site/apps/food-network-kitchen","position":7,"name":"App"},{"@type":"SiteNavigationElement","url":"https://www.foodnetwork.com/features/articles/sweepstakes-and-contests","position":8,"name":"Sweeps"},{"@type":"SiteNavigationElement","url":"https://www.foodnetwork.com/shows/tv-schedule","position":9,"name":"TV Schedule"},{"@type":"SiteNavigationElement","url":"https://www.foodnetwork.com/fn-dish","position":10,"name":"Blog"},{"@type":"SiteNavigationElement","url":"https://www.foodnetwork.com/shows/a-z","position":11,"name":"Shows A-Z"},{"@type":"SiteNavigationElement","url":"https://www.foodnetwork.com/profiles/talent","position":12,"name":"Chefs A-Z"},{"@type":"SiteNavigationElement","url":"https://www.foodnetwork.com/healthy","position":13,"name":"Healthy"},{"@type":"SiteNavigationElement","url":"https://www.foodnetwork.com/holidays-and-parties/packages/holidays","position":14,"name":"Holiday Central"},{"@type":"SiteNavigationElement","url":"https://www.foodnetwork.com/how-to/packages/shopping","position":15,"name":"Shop"}]}]</script>
</details>

Is this an issue with foodnetwork.com?

**Comment by mrzapp** [comment]
@geeseven I just tried it with the latest code from the `develop` branch, so it seems we've fixed whatever was causing the issue. When all our current issues are closed, a new patch will be published, I don't think it'll be much longer now.

Closing this issue for now.

**Comment by geeseven** [comment]
After upgrading to 0.5.5, recipes from foodnetwork.com are still not getting added.  This time with a `Could not add recipe: "Could not find recipe element"` error.  The `nextcloud.log` file also got spammed with 195 entries.  Here are the first and last two as examples:

```json
{
  "reqId": "gTMyT7k2BTZS80H607uM",
  "level": 3,                     
  "time": "2019-12-06T03:27:02+00:00",
  "remoteAddr": "127.0.0.1",
  "user": "user",
  "app": "PHP",
  "method": "POST",
  "url": "/index.php/apps/cookbook/add",
  "message": "DOMDocument::loadHTML(): Tag section invalid in Entity, line: 824 at /usr/local/www/nextcloud/apps/cookbook/lib/Service/Re
cipeService.php#351",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.13.2 Chrome/73.0.3683.105 Safari/53
7.36",
  "version": "17.0.1.1"
}
{
  "reqId": "gTMyT7k2BTZS80H607uM",
  "level": 3,
  "time": "2019-12-06T03:27:02+00:00",
  "remoteAddr": "127.0.0.1",
  "user": "user",
  "app": "PHP",
  "method": "POST",
  "url": "/index.php/apps/cookbook/add",
  "message": "DOMDocument::loadHTML(): Tag section invalid in Entity, line: 871 at /usr/local/www/nextcloud/apps/cookbook/lib/Service/Re
cipeService.php#351",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.13.2 Chrome/73.0.3683.105 Safari/53
7.36",
  "version": "17.0.1.1"
}
...
{
  "reqId": "gTMyT7k2BTZS80H607uM",
  "level": 3,                     
  "time": "2019-12-06T03:27:02+00:00",
  "remoteAddr": "127.0.0.1",
  "user": "user",
  "app": "PHP",
  "method": "POST",
  "url": "/index.php/apps/cookbook/add",
  "message": "DOMDocument::loadHTML(): Tag use invalid in Entity, line: 4852 at /usr/local/www/nextcloud/apps/cookbook/lib/Service/Recip
eService.php#351",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.13.2 Chrome/73.0.3683.105 Safari/53
7.36",
  "version": "17.0.1.1"
}
{
  "reqId": "gTMyT7k2BTZS80H607uM",
  "level": 3,
  "time": "2019-12-06T03:27:02+00:00",
  "remoteAddr": "127.0.0.1",
  "user": "user",
  "app": "PHP",
  "method": "POST",
  "url": "/index.php/apps/cookbook/add",
  "message": "DOMDocument::loadHTML(): htmlParseEntityRef: expecting ';' in Entity, line: 4903 at /usr/local/www/nextcloud/apps/cookbook
/lib/Service/RecipeService.php#351",
  "userAgent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.13.2 Chrome/73.0.3683.105 Safari/53
7.36",
  "version": "17.0.1.1"
}
```

I can supply the entire log entries if needed.

**Comment by mrzapp** [comment]
Alright, I'm seeing the issue now as well, but only for certain recipes.

**Comment by Teifun2** [comment]
For further reference, could you link one example that does not work?

**Comment by geeseven** [comment]
@Teifun2, the link from my original post is an example.  That being said, I tested like five or six random recipes from foodnetwork.com and none of them worked.

**Comment by mrzapp** [comment]
This is working in 0.6.0

**Comment by geeseven** [comment]
I am still unable to add any recipes from foodnetwork.com with 0.6.3.  Still getting the same errors as before.  Here are some random recipes I attempted to add:

https://www.foodnetwork.com/recipes/food-network-kitchen/summery-herbed-tuna-pasta-salad-5291038

https://www.foodnetwork.com/recipes/spinach-tortellini-soup-recipe-1958087

https://www.foodnetwork.com/recipes/food-network-kitchen/braised-beans-recipe-1973661

https://www.foodnetwork.com/recipes/ree-drummond/mexican-rice-casserole-recipe-2043294

Am I running into some sort of cache issue? 🤷‍♂️

**Comment by mrzapp** [comment]
@geeseven these ones work for me:

* http://www.foodnetwork.co.uk/recipes/mexican-rice-casserole.html
* http://www.foodnetwork.co.uk/recipes/spinach-tortellini-soup.html

This is not a recipe, but a category overview:

* https://www.foodnetwork.com/recipes/food-network-kitchen/braised-beans-recipe-1973661

This one has been removed from the website:

* https://www.foodnetwork.com/recipes/food-network-kitchen/summery-herbed-tuna-pasta-salad-5291038

It seems to be working as intended :man_shrugging:

**Comment by geeseven** [comment]
Hey @mrzapp,

Thanks for looking into this issue again.  I have found that foodnetwork.com and foodnetwork.co.uk are not just different domain names pointing to the same content.  

I just retested those four urls from my home ISP and from my nextcloud server and all loaded recipe pages in a browser.  In Tor Browser with a German endpoint, I could recreate the behaviour you were seeing.

I am able to add the co.uk versions of the two working recipes to the cookbook app.

Do you have access to and end point that does not redirect foodnetwork.com to foodnetwork.co.uk?

**Comment by mrzapp** [comment]
I suppose I could VPN to a server in the USA, but it won't be soon 😅 This whole thing with foodnetwork seems a bit convoluted

**Comment by geeseven** [comment]
> This whole thing with foodnetwork seems a bit convoluted

100% agree

The wayback machine does have some of the foodnetwork.com pages cached:

https://web.archive.org/web/20200322182313/https://www.foodnetwork.com/recipes/ree-drummond/mexican-rice-casserole-recipe-2043294

https://web.archive.org/web/20200329224335/https://www.foodnetwork.com/recipes/alton-brown/shepherds-pie-recipe2-1942900

**Comment by mrzapp** [comment]
Aha, I see what the issue is:

```html
<script type="application/ld+json">[{"@context":"http://schema.org","@type":"Recipe", ... }]</script>
```

They've marked up the recipe in correct ld+json, but as an `Array` with a single recipe in it, rather than the standard `Object` presentation.

So we could fix this by checking for `$json[0]` and translating it.

Reopening the issue (once again) :D

**Comment by geeseven** [comment]
Hey @mrzapp,

Did you have a change of heart regarding adding some custom code for foodnetwork.com?  If so, that is completely understandable.  

For me and I am sure plenty of other North Americans, the lack of foodnetwork.com is a deal breaker.

**Comment by mrzapp** [comment]
@geeseven no, I just fixed the issue I found with the site and I was able to import recipes just fine afterwards. If you're still having issues, you're welcome to reopen this ticket and add some details of the recipe that's failing.

**Comment by geeseven** [comment]
@mrzapp, thanks for the timely reply.  Looks like I got confused when attempting to add some recipes and mixed up some sites.  I can confirm foodnetwork.com does work for me.  Thanks for this workaround.

**Comment by uuuu1234** [comment]
Hi there,

I get the "Could not find recipe element" error message for example for the following recipe:

https://food52.com/recipes/9473-beet-orange-olive-and-walnut-salad

It works for some recipes from this source, but not all of them.

Thanks in advance

**Comment by mrzapp** [comment]
@uuuu1234 please create new issues for different sites, this is a closed issue for foodnetwork.com
